# Fortigate demo Active/Passive SDN in [${location}]

fgt_hub_ext_public_ip_address = "${fgt_hub_ext_public_ip_address}"
fgt_hub_a_private_ip_address_ext = "${fgt_hub_a_private_ip_address_ext}"
fgt_hub_a_private_ip_address_int = "${fgt_hub_a_private_ip_address_int}"
fgt_hub_a_private_ip_address_hasync = "${fgt_hub_a_private_ip_address_hasync}"
fgt_hub_a_private_ip_address_mgmt = "${fgt_hub_a_private_ip_address_mgmt}"
fgt_hub_a_public_ip_address_mgmt = "${fgt_hub_a_public_ip_address_mgmt}"
fgt_hub_b_private_ip_address_ext = "${fgt_hub_b_private_ip_address_ext}"
fgt_hub_b_private_ip_address_int = "${fgt_hub_b_private_ip_address_int}"
fgt_hub_b_private_ip_address_hasync = "${fgt_hub_b_private_ip_address_hasync}"
fgt_hub_b_private_ip_address_mgmt = "${fgt_hub_b_private_ip_address_mgmt}"
fgt_hub_b_public_ip_address_mgmt = "${fgt_hub_b_public_ip_address_mgmt}"
lnx_spoke1_private_ip_address = "${lnx_spoke1_private_ip_address}"
lnx_spoke2_private_ip_address = "${lnx_spoke2_private_ip_address}"